CREATE TABLE IF NOT EXISTS humanresources.address (
  addressid        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addressline1     varchar NOT NULL,
  addressline2     varchar,
  city             varchar NOT NULL,
  stateprovinceid  integer, -- FK possible vers humanresources.stateprovince(id)
  postalcode       varchar,
  spatiallocation  bytea,
  rowguid          uuid DEFAULT gen_random_uuid(),
  modifieddate     timestamp without time zone DEFAULT now()
);